[tools]
'aqua:neovim/neovim' = "0.11.5"
go = "1.24"
python = "3.12"
node = "lts"
opencode="latest"
uv = "latest"
jq = "latest"
yq = "latest"
fzf = "latest"
ripgrep = "latest"
zoxide = "latest"
lazygit = "latest"
k9s = "latest"
ruff = "latest"
argocd = "latest"
kubectl = "latest"
kubectx = "latest"
crictl = "latest"
golangci-lint = "latest"
starship = "latest"
eza = "latest"
dyff = "latest"
pipx = "latest"  # for installing python tools, e.g. ansible
ansible="latest"
bun = "1.3.13"
github-cli = "2.91.0"
d2 = "latest"
rtk = "latest"
