[tools]
neovim = "0.11.5"
go = "1.24"
python = "3.12"
node = "lts"
opencode="latest"
uv = "latest"
jq = "latest"
yq = "latest"
fzf = "latest"
ripgrep = "latest"
zoxide = "latest"
lazygit = "latest"
k9s = "latest"
ruff = "latest"
argocd = "latest"
helm = "latest"
kubectl = "latest"
kubectx = "latest"
crictl = "latest"
golangci-lint = "latest"
starship = "latest"
eza = "latest"
